### ISSUE TITLE
RAutomation on 64bit Ruby

### ISSUE THREAD

**Issue by codyssius** [jarmo/RAutomation#102]
Referencing #68 - I was just wondering if there was anything underway to make RAutomation compatible with 64bit Ruby? I'm having the same issue but am unable to switch to 32bit Ruby for what I'm doing.

**Comment by leviwilson** [comment]
I've not revisit this for awhile; there are some things that I'm not sure how to do, but there would be a decent amount of work to make this x64 compatible if I recall correctly. I believe we'd have to package different binaries depending on your architecture (I don't really know how to do this).

It's not that it's impossible, but tl;dr; nothing has been done towards this effort.

**Comment by codyssius** [comment]
Okay I understand. Thanks for the reply. I'll try to figure out a different solution or workaround on my end.

**Comment by leviwilson** [comment]
@codyssius anytime...I definitely would like to look into this at some point but haven't revisit for awhile. If I'm afforded some time to look into this at some point I'll re-open this.
