### ISSUE TITLE
ToolbarWindow32 class having three buttons , i need click on second button , not able to click on it 

### ISSUE THREAD

**Issue by KMadhuSudhan** [jarmo/RAutomation#112]
In Excel , i got below info from Auto IT

>>>> Control <<<<
Class:  ToolbarWindow32
Instance:   1
ClassnameNN:    ToolbarWindow321
Name:   
Advanced (Class):   [CLASS:ToolbarWindow32; INSTANCE:1]
ID: 
Text:   
Position:   304, 79
Size:   615, 28
ControlClick Coords:    45, 14
Style:  0x52001101
ExStyle:    0x00000000
Handle: 0x0003047A

**Comment by leviwilson** [comment]
Can you please provide more information about the issue that you're having? Closing until further information can be provided about the issue that you're having.

**Comment by KMadhuSudhan** [comment]
refer this
 https://www.autoitscript.com/forum/topic/125795-controlclick-toolbarwindow32/


i need to achieve same with RAutomation
