### ISSUE TITLE
ToolbarWindow32 class having three buttons , i need click on second button , not able to click on it 

### ISSUE THREAD

**Issue by KMadhuSudhan** [jarmo/RAutomation#113]
Hi,
Please help me in this 
 i need to click on drop down as shown in the screen shot . drop down class name 
 ToolbarWindow32. Since this class is common for all three elements, not able to click on second button . After clicking on dropdwon button , i need to click on disconnect all
![sceenshotsharedconn](https://cloud.githubusercontent.com/assets/5602017/25110249/09442364-2400-11e7-84be-073e00a9f557.png)

**Comment by jarmo** [comment]
Please write all support questions to StackOverflow instead of reporting it here as an issue. Closing this.
