### ISSUE TITLE
No such file to load 

### ISSUE THREAD

**Issue by MonsterMetroid** [jarmo/RAutomation#119]
I am getting an error that says no such file to load -- page-object/platforms/rautomation_driver (LoadError). Anyone have any insight on this?

**Comment by enkessler** [comment]
At first glance, it sounds like a problem in `page-object`.

**Comment by enkessler** [comment]
@MonsterMetroid Are you trying to load `page-object/platforms/rautomation_driver` or is that coming from an external library?

**Comment by MonsterMetroid** [comment]
I think it is from an external Library

**Comment by enkessler** [comment]
Well, looking over at the `page-object` repository, there really I no file at `lib/page-object/platforms/rautomation_driver`, so the error makes sense. What makes less sense is why `page-object` would be trying to pull that in. Unless you're working with old versions and trying to use `water-classic` or something.

Try getting a full stack trace. That should make it clear what code is trying to load that file.

**Comment by jarmo** [comment]
Closing this since it is not a RAutomation issue.
