### ISSUE TITLE
Unable to upgrade 

### ISSUE THREAD

**Issue by aswerlein511** [jarmo/RAutomation#125]
I am trying to upgrade my Ruby language to version 2.5.5.1.  When doing this, the FFI gem dependency ~>1.9.0 becomes incompatible with the language.  Is there a reason this dependency is present?  Is there a way to update RAutomation to allow for the newer version of ffi (1.11.1) to allow for an upgrade to my Ruby language?

**Comment by leviwilson** [comment]
FFI is the bridge to communicate with native dependencies; it's different depending on which driver you're using but it is required by all drivers to communicate between ruby / C++ DLLs.

You can try to bump the dependency to see if all the specs pass with it; I don't believe anyone else has looked into this recently.

**Comment by jarmo** [comment]
Newest ffi can now be used in the gem version 1.0.0.
